%% NULL LENS DESIGN

%{
35.2 spherical aberration generated by a parabolic mirror
W040 = -1/32*y^4*phi^3


%}

% example 
f = 364;
phi = 1/f;
y = 91/2;
lambda = 0.6328;

W040 = -1/32*y^4*phi^3;

Wavenumber = W040/lambda*1e4;



%{
35.5 derivation of surface normals for parabolic mirror
delta_N = (1-P)*z
parabola  P = 1+K = 0
delta_N = z = y^2/(2*R) = sag

tan(theta) = -y/R
delta_N = R/2*tan(theta)^2

%}
R = 728;
theta = [0.895, 1.790, 2.684, 3.576]*pi/180;

y = R*tan(theta);
delta_N = R/2*tan(theta).^2;


%{
another way
W040N = 1/2*W040 ?WHY
W040N = DFS
delta = 8*F_number^2*Wd


%}

%example

u_ = atan(91/2/R);
F_number = 1/2/u_;

Wd = -2*W040;
W040N = 1/2*Wd;
delta_N1 = 8*F_number^2*W040N;



%{
33.6 The offner null lens
generator and tuner
crucial: the generator lens be placed beyond the parabola's surface normal
caustic(1/2 ray caustic)

Given t_GT, obtain the diameter of generator


%}
% UNIT: cm

f = 364;
D = 91;


t_GT = 360*0.1;
y_G = t_GT*tan(3.576/180*pi);
l_G_ = t_GT;
m_G = -0.6147;


l_G = l_G_/m_G;
phi_G = -1/l_G+1/l_G_;
f_G = 1/phi_G;

X = -1;
Y = (1+m_G)/(1-m_G);
sigma_1 = 8.7444*X^2 - 12.8912*X*Y +4.32*Y^2 + 8.6519;
W040G = 1/32*y_G^4*phi_G^3*sigma_1;

% GENERATOR
n_G = 1.5168;
R_G = -(n_G-1)/phi_G;


% TUNER
% UNIT mm
l_T = -351.325;
l_T_ = 2*f*10;
phi_T = -1/l_T+1/l_T_;

R_T = -(n_G-1)/phi_T;

